# Generated by Django 3.2 on 2021-04-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_app_form_bus_type_master_consession_details_depot_master_feedback_institution_master_rate_master_rou'),
    ]

    operations = [
        migrations.AddField(
            model_name='consession_details',
            name='c_number',
            field=models.CharField(default='00', max_length=100),
            preserve_default=False,
        ),
    ]
