# Generated by Django 3.2 on 2021-04-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_consession_details_c_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='consession_details_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('c_number', models.CharField(max_length=100)),
                ('stage_rate', models.FloatField()),
                ('dt', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('no_months', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
